FFT: id instead of url
UU-tracktech/tracktech pull request #119
Opened 2021-06-08 07:13 UTC by JTeeuwissen

2021-06-09 12:54 UTC, GerardvSchie submitted a review, later dismissed

2021-06-09 13:04 UTC, mvdhart requested changes

2021-06-09 13:04 UTC, mvdhart commented on CameraProcessor/processor/utils/config_parser.py
> +        self.configs['Input']['camera_id'] = os.getenv('CAMERA_ID')
for both of these please add them to configs.ini as well for now with a standard value and use "or" here

2021-06-09 15:08 UTC, GerardvSchie approved these changes

2021-06-09 15:09 UTC, Sxord approved these changes

2021-06-09 15:45 UTC, saberzero1 approved these changes

2021-06-10 11:35 UTC, mvdhart approved these changes

2021-06-10 19:08 UTC, merged