FFT: Remove camera id from the configs.ini
UU-tracktech/tracktech pull request #146
Opened 2021-06-12 22:02 UTC by GerardvSchie

Camera id should not be in configurations of cameraprocessor since it is required to be specified inside environment
Otherwise it is possible to mistakenly start up camera processor without being guaranteed to have thought about the ID

2021-06-12 22:26 UTC, mvdhart submitted a review, later dismissed

2021-06-12 22:27 UTC, mvdhart commented
Mention this change in camera-processor when this is merged

2021-06-12 23:04 UTC, saberzero1 submitted a review, later dismissed

2021-06-13 06:34 UTC, JTeeuwissen requested changes
How about the hls url? This should be environment only as well. The same goes for orchestrator url.

2021-06-14 12:14 UTC, saberzero1 approved these changes

2021-06-14 15:47 UTC, merged