Spc 550 dataloader classes for test train and verify data
UU-tracktech/tracktech pull request #148
Opened 2021-06-13 11:46 UTC by saberzero1

2021-06-15 20:55 UTC, GerardvSchie submitted a review, later dismissed

2021-06-17 08:06 UTC, bacdekker requested changes
Changes heb ik met Emile en Marieke besloten, maar in ieder geval:

Append box moet een box meekrijgen en je moet het appenden bij een dictionary om het te sorteren
Een functie moet naar utils verplaatst worden
Mot moet ingelezen kunnen worden zonder image width, hight.

2021-06-17 12:46 UTC, bacdekker approved these changes
Zag er goed uit, al mijn requested changes zitten er in

2021-06-17 14:29 UTC, Sxord requested changes

2021-06-17 14:29 UTC, Sxord commented on CameraProcessor/configs.ini
> +[COCO]
comments voor gegeven config waardes missen

2021-06-17 14:29 UTC, Sxord commented on CameraProcessor/configs.ini
> +[MOT]
comments voor gegeven config waardes missen

2021-06-17 14:29 UTC, Sxord commented on CameraProcessor/configs.ini
> +[JSON]
comments voor gegeven config waardes missen

2021-06-17 16:47 UTC, GerardvSchie approved these changes

2021-06-17 17:10 UTC, GerardvSchie approved these changes

2021-06-17 17:10 UTC, GerardvSchie commented
Clean code = happy code :)

2021-06-17 18:28 UTC, Sxord approved these changes

2021-06-17 18:29 UTC, merged