Spc 836 refactor websocket client api
UU-tracktech/tracktech pull request #174
Opened 2021-06-16 21:34 UTC by mvdhart

2021-06-16 23:04 UTC, Li-Yeun approved these changes

2021-06-17 05:47 UTC, saberzero1 requested changes
The marked files contain qoutations marks rather than single qoutes. Yesterday the all python files were refactored for this. Please fix.

(I have not marked every instance of qoutation marks, but every file with incorrect qoutations has been marked)

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/boxes_message.py
> +            raise KeyError("objectId missing")
Single qoutes svp

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/boxes_message.py
> +            "type": "boundingBoxes",
Same here

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/i_message.py
> +        raise NotImplementedError("Expected function to_message not implemented.")
Single qoutes

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/start_message.py
> +            raise TypeError("Frame id should be a float")
Single qoutes

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/stop_message.py
> +            str: String representation of a StopMessage.
Single qoutes

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/update_message.py
> +        if not isinstance(object_id, int):
Single qoutes

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/processor/websocket/websocket_client.py
> +                "start": StartMessage,
Single qoutes

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/tests/orchestratorintegrationtests/test_receiving_from_orchestrator.py
> +    @pytest.mark.skip("Refactored commands")
Single qoutes

2021-06-17 05:47 UTC, saberzero1 commented on CameraProcessor/tests/orchestratorintegrationtests/test_send_to_orchestrator.py
> +    @pytest.mark.skip("Refactored commands")
Single qoutes

2021-06-17 07:37 UTC, saberzero1 approved these changes

2021-06-17 08:34 UTC, GerardvSchie approved these changes

2021-06-17 08:38 UTC, merged