FFT: Removed keycloak and added generic oauth2 client
UU-tracktech/tracktech pull request #202
Opened 2021-06-21 15:41 UTC by RienkF

Changed the tests as well to accomodate the new structure.

Updated readme and removed now obsolete installs.

2021-06-21 15:57 UTC, JTeeuwissen approved these changes

2021-06-21 17:15 UTC, BrianVanB commented on Interface/react/src/components/environmentContext.tsx
> +        segmentLength: environment?.segmentLength ?? 1,
Is de default segmentLength bij de forwarder niet 2?

2021-06-21 17:20 UTC, BrianVanB requested changes
Aangezien keycloak er nu uit is kan de __mocks__ map ook weg, want de keycloak mock is toch niet meer nodig

2021-06-21 17:55 UTC, RienkF commented on Interface/react/src/components/environmentContext.tsx
> +        segmentLength: environment?.segmentLength ?? 1,
Ja, maar dat is onze forwarder, dus het leek me gek om dat soort specifieke dingen er in te zetten. Heb nu gewoon default alles met n 1. Opzich kan buffertime dat bijv ook

2021-06-22 10:19 UTC, RienkF commented
> Aangezien keycloak er nu uit is kan de __mocks__ map ook weg, want de keycloak mock is toch niet meer nodig

Well spotted, is aangepast

2021-06-22 10:22 UTC, BrianVanB approved these changes

2021-06-22 10:33 UTC, JTeeuwissen approved these changes

2021-06-22 10:33 UTC, Marieke-van-der-Plaat commented on Interface/react/src/components/authContext.tsx
> +/*
Bij python enforcen we dat aan het begin van deze docstring staat waar het bestand voor is. Moet dat hier ook?

2021-06-22 10:36 UTC, RienkF commented on Interface/react/src/components/authContext.tsx
> +/*
Nee, dat zou heel dubbel zijn. Vrijwel elk bestand heeft maar 1 component of class en die class moet een jdoc comment hebben, dat is voldoende

2021-06-22 10:37 UTC, merged