Spc 551 create tracking timeline overview page
UU-tracktech/tracktech pull request #67
Opened 2021-05-26 14:50 UTC by RienkF

2021-05-26 15:03 UTC, JTeeuwissen requested changes
geen flexbox maar grid

2021-05-26 16:49 UTC, BrianVanB approved these changes

2021-05-26 19:10 UTC, JTeeuwissen commented on Interface/react/src/classes/timelineData.ts
> +      if (spottedOn[logEvent.processorId] == undefined) {
haal == undefined weg

2021-05-26 19:11 UTC, JTeeuwissen commented on Interface/react/src/pages/timelines.tsx
> +    fetch('https://tracktech.ml:50011/objectIds').then((text) =>
hier moet ook nog iets beters voor komen

2021-05-26 19:12 UTC, JTeeuwissen commented on Interface/react/src/pages/timelines.tsx
> +        if (text.status == 400) {
is het bij een 400 niet een error?

2021-05-27 19:52 UTC, RienkF commented on Interface/react/src/pages/timelines.tsx
> +        if (text.status == 400) {
400 is bad request. Vragen om een object dat niet bestaat zie ik als bad request

2021-05-27 19:52 UTC, RienkF commented on Interface/react/src/pages/timelines.tsx
> +        if (text.status == 400) {
En die heb ik zelf bij de orchestrator gemaakt

2021-05-27 19:53 UTC, RienkF commented on Interface/react/src/pages/timelines.tsx
> +    fetch('https://tracktech.ml:50011/objectIds').then((text) =>
Hoe bedoel je beter? Je fetched en je doet wat met het resultaat. maybe env variable maar dat is niet echt leuk met react

2021-05-27 20:02 UTC, RienkF commented on Interface/react/src/classes/timelineData.ts
> +      if (spottedOn[logEvent.processorId] == undefined) {
Adressed

2021-05-27 20:09 UTC, JTeeuwissen requested changes
PLease remove == undefined elsewhere too

2021-05-27 20:18 UTC, JTeeuwissen requested changes

2021-05-27 20:18 UTC, JTeeuwissen commented on Interface/react/src/pages/timelines.tsx
> +  ] = React.useState<TimelineData | null>(new TimelineData([]))
Why can this be null?

2021-05-28 10:49 UTC, BrianVanB submitted a review, later dismissed

2021-05-28 12:20 UTC, BrianVanB approved these changes

2021-05-28 12:26 UTC, Sxord approved these changes

2021-05-28 12:26 UTC, merged