Spc 665 cutout of bounding box
UU-tracktech/tracktech pull request #68
Opened 2021-05-26 19:08 UTC by JTeeuwissen

2021-05-26 21:34 UTC, BrianVanB approved these changes

2021-05-27 11:10 UTC, Li-Yeun approved these changes

2021-05-27 20:23 UTC, RienkF requested changes

2021-05-27 20:23 UTC, RienkF commented on Interface/react/src/classes/orchestratorMessage.ts
> +    frameId: number,
frameId and boxId should also be optional, if you want to adhere to the orchestrator protocol. Unless you want to build the image based on what this interface will send, but in that case image should not be optional

2021-05-27 20:23 UTC, RienkF commented on Interface/react/src/classes/orchestratorMessage.ts
> +    frameId: number,
frameId and boxId should be optional, if you want to adhere to orchestrator protocol. If you want to adhere to what this interface will send, then the image should not be optional

2021-05-27 20:39 UTC, JTeeuwissen commented on Interface/react/src/classes/orchestratorMessage.ts
> +    frameId: number,
No, frameId and boxId are always send and optionality does not provide any benefits. And image should be optional due to the snapping ref being possibly undefined, and then we still would like to send the camera-/frameid.

2021-05-27 20:40 UTC, merged